### ISSUE TITLE
别把提问的智慧当圣经

### ISSUE THREAD

**Issue by Cchen-77** [BY-H/Introduction-of-CS-Major#1]

**Comment by BY-H** [comment]
还有啥别的推荐吗？主要是有些伸手党就比较逆天

**Comment by Cchen-77** [comment]
> 还有啥别的推荐吗？主要是有些伸手党就比较逆天

还是看场景吧。主要是很多人当圣经了

**Comment by Cchen-77** [comment]
> > 还有啥别的推荐吗？主要是有些伸手党就比较逆天
> 
> 还是看场景吧。主要是很多人当圣经了

在群发场景下，很多人喜欢STFW + 提问的智慧。没啥必要。1v1场景下我支持提问的智慧

**Comment by Cchen-77** [comment]
作为一个提问者，你应该学习提问的智慧
作为一个被提问者，你不应该把提问的智慧当圣经

**Comment by BY-H** [comment]
> 作为一个提问者，你应该学习提问的智慧 作为一个被提问者，你不应该把提问的智慧当圣经

正确的

**Comment by nevermind-bit** [comment]
其实会提问，已经解决了 90% 的问题
